require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'


Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: e

RSpec/MultipleExpectations:
  Enabled: false